import 'package:freedom_wallet/data/local/alert_storage.dart';
import 'package:freedom_wallet/domain/interfaces/alert_service.dart';
import 'package:freedom_wallet/domain/models/alert.dart';

/// AlertService backed by persistent local storage.
///
/// Alerts are generated by the vault monitor when blockchain state changes,
/// and persisted so they survive app restarts.
class BlockchainAlertService implements AlertService {
  final AlertStorage _storage;
  List<Alert> _alerts = [];
  bool _loaded = false;

  BlockchainAlertService({AlertStorage? storage})
      : _storage = storage ?? AlertStorage();

  Future<void> _ensureLoaded() async {
    if (_loaded) return;
    _alerts = await _storage.loadAlerts();
    _loaded = true;
  }

  @override
  Future<List<Alert>> getAlerts() async {
    await _ensureLoaded();
    return List.unmodifiable(_alerts);
  }

  @override
  Future<void> addAlert(Alert alert) async {
    await _ensureLoaded();
    _alerts = [alert, ..._alerts];
    await _storage.saveAlerts(_alerts);
  }

  @override
  Future<void> acknowledgeAlert(String alertId) async {
    await _ensureLoaded();
    _alerts = _alerts.map((a) {
      if (a.id == alertId) {
        return a.copyWith(acknowledged: true);
      }
      return a;
    }).toList();
    await _storage.saveAlerts(_alerts);
  }

  @override
  int get unacknowledgedCount =>
      _alerts.where((a) => !a.acknowledged).length;
}
